"""add categories to source documents

Revision ID: 160a79baf92b
Revises: 8f35814e860f
Create Date: 2026-06-13 08:50:02.743409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160a79baf92b'
down_revision: Union[str, Sequence[str], None] = '8f35814e860f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('categories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'categories')
    # ### end Alembic commands ###
