"""add category

Revision ID: 22f526ae4fda
Revises: 8d1c090b16eb
Create Date: 2026-06-13 05:34:54.167414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f526ae4fda'
down_revision: Union[str, Sequence[str], None] = '8d1c090b16eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_items', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('source_items', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_items', 'category')
    op.drop_column('check_items', 'category')
    # ### end Alembic commands ###
