"""remove_embedding

Revision ID: 8d1c090b16eb
Revises: edd35fd99bf1
Create Date: 2026-06-13 05:22:53.474020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8d1c090b16eb'
down_revision: Union[str, Sequence[str], None] = 'edd35fd99bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_items', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_items', sa.Column('embedding', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
