"""Initial migration

Revision ID: edd35fd99bf1
Revises: 
Create Date: 2026-06-11 20:05:21.223685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd35fd99bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_a_path', sa.String(length=512), nullable=False),
    sa.Column('prompt_template_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('context_text', sa.String(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('source_hint', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('check_item_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ai_reasoning', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['check_item_id'], ['check_items.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_table('check_items')
    op.drop_table('source_items')
    op.drop_table('check_sessions')
    op.drop_table('source_documents')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
